FROM openjdk:8
ENV RUN_ARGS="--server.port=80 --server.ssl.enabled=false"
RUN cd /tmp/ && curl -kO https://bootstrap.pypa.io/get-pip.py && python get-pip.py --trusted-host pypi.org --trusted-host files.pythonhosted.org && pip install awscli --trusted-host pypi.org --trusted-host files.pythonhosted.org && cd -
COPY entrypoint.sh ./entrypoint.sh
RUN chmod +x ./entrypoint.sh
#ENTRYPOINT ["./entrypoint.sh"]

